### ISSUE TITLE
Longer Domains broken

### ISSUE THREAD

**Issue by cno-dev** [hdoro/sanity-plugin-prefixed-slug#1]
If my BasePath is longer it gets cut off.
Maybe a scroll overflow-x would be a good start to at least be able to read it completely, or make the basepath wrap?

**Comment by hacknug** [comment]
Using tooltips or a similar pattern might also be helpful in some contexts.

**Comment by ovsw** [comment]
Merge, please? 🙏

**Comment by hdoro** [comment]
Fixing this with the release of `sanity-plugin-prefixed-slug`, the new version of this plugin.

Sorry for the wait y'all!

<img width="669" alt="2022-07-15-Firefox Developer Edition@2x" src="https://user-images.githubusercontent.com/27744332/179241733-242546d7-4882-47b9-8a76-c90c51cc75c0.png">

**Comment by ovsw** [comment]
@hdoro I installed the new version, but there's a weird artefact in the UI, see image below:
![image](https://user-images.githubusercontent.com/35622133/179263862-a00698aa-79d5-4d81-9fa4-fdcdd29e6007.png)

Seems to be the "after" element visible in the open console in the screenshot. No ideea why it's there. I did remove the previous plugin with `sanity uninstall better-slug`
