### ISSUE TITLE
@->slug returns the slug without the base url

### ISSUE THREAD

**Issue by vin-ni** [hdoro/sanity-plugin-prefixed-slug#4]
How can I return the slug + baseUrl while using `groq`.

```
*[_type == "about"] {
  aboutText[]{...,
      markDefs[]{
      ...,
      _type == "internalLink" => {
        "slug": @->slug,
      }
    }
  }
}
```

Thanks :)

**Comment by schellenbergk** [comment]
Same question here

**Comment by devinhalladay** [comment]
@hdoro are you still maintaining this library?

**Comment by hdoro** [comment]
The base URL is purely visual. No data is stored in Sanity, instead the library assumes that, if you can generate the prefix URL in the studio, you can generate it in the front-end.

This is to ensure we don't encode into data what could eventually be changed across the entire dataset, such as domain dames, routes and paths. Let me know if this isn't clear, glad to do a write-up!

**Comment by toddpadwick** [comment]
@hdoro  I think this is still a valid requirement – let's say you have multiple front end applications, all of which renders the same list of entries from the Sanity API – such as:

1. A SaaS application, which has a section that shows some help articles or guides - app built and managed by product team.
2. A automated email newsletter which is generated automatically from the sanity API showing latest blog articles. Newsletter managed by the marketing team.
3. And of course, the marketing website. Managed by myself.
All three of the above, are managed by different dev teams, but need to have access to the same URI paths, which can be complex, such as `/blog/category/subcategory/slug`, leading to the marketing site. So having a function to generate this on all three, would be error prone and means code is repeated and has to be manually passed between different developers – very error prone and hard to track when uri's might change.
