### ISSUE TITLE
Weird UI artefact in new version

### ISSUE THREAD

**Issue by ovsw** [hdoro/sanity-plugin-prefixed-slug#7]
@hdoro I installed the new version, but there's a weird artefact in the UI, see image below:
![image](https://user-images.githubusercontent.com/35622133/179263862-a00698aa-79d5-4d81-9fa4-fdcdd29e6007.png)

Seems to be the "after" element visible in the open console in the screenshot. No ideea why it's there. I did remove the previous plugin with `sanity uninstall better-slug`

**Comment by hdoro** [comment]
Thank you for reporting, Ovi! Will try to get to it by the end of next week - hope it doesn't break UX for you until then 🤞

**Comment by danielskogstad** [comment]
Installed your plugin today and we are experiencing the same issue. Any solutions?

**Comment by hdoro** [comment]
Fixed in `^2.0.0` (for Sanity V3 only) :)
