### ISSUE TITLE
URLPrefix ends with "/" 

### ISSUE THREAD

**Issue by Mikaila94** [hdoro/sanity-plugin-prefixed-slug#8]
I noticed that the URL-prefix ends with a "/", but this may not be desirable in other cases.  In my case I want to use a '#'.
This is the code that causes the problem:

const finalPrefix = `${urlPrefix}${urlPrefix?.endsWith('/') ? '' : '/'}`

**Comment by hdoro** [comment]
Thank you for reporting, Mikail!

I've removed the trailing slash if the URL includes a hash (`site.com/#slug-is`) or a query parameter (`site.com/?page-id=`) 😊
