### ISSUE TITLE
urlPrefix should be called on document changes

### ISSUE THREAD

**Issue by leo-cheron** [hdoro/sanity-plugin-prefixed-slug#9]
It seems urlPrefix is never called on document changes, which prevents the prefix from being updated without refreshing the page.

Let's say I declare the input with the following code:

```
{
      name: 'slug_function_path',
      type: 'slug',
      inputComponent: SlugInput,
      options: {
        urlPrefix: (document) => `https://site.url/${document.lang}`,
        isUnique: isUniqueAccrossPages(slug, options),
      },
},
```

Updating the lang field of the document will call isUniqueAccrossPages, but not the urlPrefix function, thus won't update the value of the prefix accordingly.

**Comment by hdoro** [comment]
Sorry for the wait, Léo!

This is being fixed the the Sanity v3 version of the plugin (`^2.0.0`), thank you for reporting! Keep in mind there's an upstream where [input components can't access the freshest version of the document](https://github.com/sanity-io/sanity/issues/3606), so your prefix will always be one edit behind the document.
